#fondo.py solo guarda rutas de fondos.
import os

fondo_prueba = os.path.join(os.path.dirname(os.path.dirname(__file__)), "mapas", "fondo_prueba.png")
mapa1_cerrada = os.path.join(os.path.dirname(os.path.dirname(__file__)), "mapas", "mapa1_pcerrada.png")
mapa1_abierta = os.path.join(os.path.dirname(os.path.dirname(__file__)), "mapas", "mapa1_pabierta.png")
mapa2 = os.path.join(os.path.dirname(os.path.dirname(__file__)), "mapas", "mapa2.png")
mapa3 = os.path.join(os.path.dirname(os.path.dirname(__file__)), "mapas", "mapa3.png")
m1_opciones = os.path.join(os.path.dirname(os.path.dirname(__file__)), "mapas", "m1_opciones.png")
m2_opciones = os.path.join(os.path.dirname(os.path.dirname(__file__)), "mapas", "m2_opciones.png")
m3_opciones = os.path.join(os.path.dirname(os.path.dirname(__file__)), "mapas", "m3_opciones.png")
key = os.path.join(os.path.dirname(os.path.dirname(__file__)), "mapas", "key.png")
cofre_a= os.path.join(os.path.dirname(os.path.dirname(__file__)), "mapas", "cofre_a.png")
cofre_c= os.path.join(os.path.dirname(os.path.dirname(__file__)), "mapas", "cofre_c.png")
nota= os.path.join(os.path.dirname(os.path.dirname(__file__)), "mapas", "nota.png")
resume_button=os.path.join(os.path.dirname(os.path.dirname(__file__)), "mapas", "resume_button.png")
settings_button=os.path.join(os.path.dirname(os.path.dirname(__file__)), "mapas", "settings_button.png")
help_button=os.path.join(os.path.dirname(os.path.dirname(__file__)), "mapas", "help_button.png")
save_button=os.path.join(os.path.dirname(os.path.dirname(__file__)), "mapas", "save_button.png")
quit_button=os.path.join(os.path.dirname(os.path.dirname(__file__)), "mapas", "quit_button.png")
menu_pause=os.path.join(os.path.dirname(os.path.dirname(__file__)), "mapas", "menu_pause.png")
button_game1=os.path.join(os.path.dirname(os.path.dirname(__file__)), "mapas", "game1_button.png")
button_game2=os.path.join(os.path.dirname(os.path.dirname(__file__)), "mapas", "game2_button.png")
button_game3=os.path.join(os.path.dirname(os.path.dirname(__file__)), "mapas", "game3_button.png")
button_game4=os.path.join(os.path.dirname(os.path.dirname(__file__)), "mapas", "game4_button.png")
button_game5=os.path.join(os.path.dirname(os.path.dirname(__file__)), "mapas", "game5_button.png")
button_empty=os.path.join(os.path.dirname(os.path.dirname(__file__)), "mapas", "game_empty_button.png")
img_boss=os.path.join(os.path.dirname(os.path.dirname(__file__)), "mapas", "img_boss.png")
img_jug=os.path.join(os.path.dirname(os.path.dirname(__file__)), "mapas", "img_jugador.png")
engranajes_foto=os.path.join(os.path.dirname(os.path.dirname(__file__)), "mapas", "engranajes.png")
vida_jugador = os.path.join(os.path.dirname(os.path.dirname(__file__)), "mapas", "vida-jugador.png")